blog/urls.py
from django.conf.urls import patterns, url

from blog import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='blog-article-index'),
    url(r'^(?P<slug>[\w\-]+)/$', views.single, name='blog-article-single'),                   
    url(r'^archive/(?P<year>\d{4})/(?P<month>\d{2})/$', views.date_archive, name='blog-date-archive'),
    url(r'^archive/(?P<slug>[-\w]+)/$', views.category_archive, name='blog-category-archive'),
)

fdjango/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'fdjango.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
                    
    url(r'^blog/', include('blog.urls', namespace='blog')),                     

    url(r'^markdown/', include( 'django_markdown.urls')),                   
                       
    url(r'^admin/', include(admin.site.urls)),
)

blog/models.py
from django.db import models

from markdown import markdown

class Category(models.Model) :
    
    title = models.CharField(max_length = 255)
    slug = models.SlugField(
        verbose_name = 'Slug',
        help_text = 'Uri identifier.',
        max_length = 255,
        unique = True
    )
    
    class Meta:
        app_label = 'blog'
        verbose_name = "Category"
        verbose_name_plural = "Categories"
        ordering = ['title',]
    
    def __str__(self):
        return "%s" % (self.title,) #Convert to string.

class Article(models.Model) :
    
    title = models.CharField(max_length = 255)
    slug = models.SlugField(
        verbose_name = 'Slug',
        help_text = 'Uri identifier.',
        max_length = 255,
        unique = True
    )
    content_markdown = models.TextField(
        verbose_name = 'Content (Markdown)',
    )
    content_markup = models.TextField(
        verbose_name = 'Content (Markup)',
    )
    categories = models.ManyToManyField(
        Category,
        verbose_name = 'Categories',
        null = True,
        blank = True
    )
    date_publish = models.DateTimeField(
        verbose_name = 'Publish Date',
    )
    
    class Meta:
        app_label = 'blog'
        verbose_name = 'Article'
        verbose_name_plural = 'Articles'
        ordering = ['-date_publish']
        
    def save(self):
        self.content_markup = markdown(self.content_markdown, ['codehilite'])
        super(Article, self).save()
        
    def __str__(self):
        return "%s" % (self.title,) #Convert to string.
        
        

blog/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404
import calendar, datetime

from blog.models import Category, Article


def index(request) :
    
    """ The Index """
    archive_dates = Article.objects.datetimes('date_publish','month', order='DESC')
    categories = Category.objects.all()

    page = request.GET.get('page')
    article_queryset = Article.objects.all()
    paginator = Paginator(article_queryset, 5)

    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        articles = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        articles = paginator.page(paginator.num_pages) 

    return render(
        request,
        "blog/article/index.html",
        {
            "articles" : articles,
            "archive_dates" : archive_dates,
            "categories" : categories
        }
    )


def single(request, slug) :
    
    """A single article"""
    article = get_object_or_404(Article, slug=slug)
    archive_dates = Article.objects.datetimes('date_publish','month', order='DESC')
    categories = Category.objects.all()
    return render(
        request,
        "blog/article/single.html",
        {
            "article" : article,
            "archive_dates" : archive_dates,
            "categories" : categories
        }
    )


def date_archive(request, year, month) :
    
    """The blog date archive"""
    # this archive pages dates
    year = int(year)
    month = int(month)
    month_range = calendar.monthrange(year, month)
    start = datetime.datetime(year=year, month=month, day=1)
    end = datetime.datetime(year=year, month=month, day=month_range[1])
    archive_dates = Article.objects.datetimes('date_publish','month', order='DESC')
    categories = Category.objects.all()

    # Pagination
    page = request.GET.get('page')
    article_queryset = Article.objects.filter(date_publish__range=(start.date(), end.date()))
    paginator = Paginator(article_queryset, 5)

    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        articles = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        articles = paginator.page(paginator.num_pages)

    return render(
        request,
        "blog/article/date_archive.html",
        {
            "start" : start,
            "end" : end,
            "articles" : articles,
            "archive_dates" : archive_dates,
            "categories" : categories
        }
    )


def category_archive(request, slug):
    archive_dates = Article.objects.datetimes('date_publish','month', order='DESC')
    categories = Category.objects.all()
    category = get_object_or_404(Category, slug=slug)

    # Pagination
    page = request.GET.get('page')
    article_queryset = Article.objects.filter(categories=category)
    paginator = Paginator(article_queryset, 5)

    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        articles = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        articles = paginator.page(paginator.num_pages)
    
    return render(
        request,
        "blog/article/category_archive.html",
        {
            "articles" : articles,
            "archive_dates" : archive_dates,
            "categories" : categories,
            "category" : category
        }
    )

blog/templates/blog/article/category_archive.html
{% extends "blog/base.html" %}

{% block title %}Archive: {{ category.title }} | Blog | {{ block.super }}{% endblock%}

{% block breadcrumb %}
<ul class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li><a href="{% url 'blog:blog-article-index' %}">Blog</a></li>
  <li class="active">Archive: {{ category.title }}</li>
</ul>
{% endblock %}

{% block content %}
<div>
    <div class="col-md-10">
        <h3>Blog Category: {{ category.title }}</h3>
        {% for item in articles %}
        <br>
        <article class="news-item">
            <h4 class="title"><a href="{% url 'blog:blog-article-single' slug=item.slug %}">{{ item.title }}</a></h4>
            <div class="meta">{{ item.date_publish|date:"F j, Y" }}</div>
            <div class="text">
                <p>{{ item.excerpt|safe }}</p>
            </div>
        </article>
        {% endfor %}

        <div class="pagination pull-right">
            <span class="step-links">
                {% if articles.has_previous %}
                    <a href="?page={{ articles.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ articles.number }} of {{ articles.paginator.num_pages }}.
                </span>

                {% if articles.has_next %}
                    <a href="?page={{ articles.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>

    </div>
    
    <div class="col-md-2">
        <ul class="nav nav-list">
        {% if archive_dates|length > 0%}
            <li class="nav-header">Archive Dates</li>
            {% for date in archive_dates %}
            <li{% if date.month == start.month and date.year == start.year %} class="active"{% endif %}><a href="{% url 'blog:blog-date-archive' month=date|date:'m' year=date|date:'Y' %}">{{ date|date:"M Y" }}</a></li>
            {% endfor %}
            <li class="nav-header">Categories</li>
            {% for tmp in categories %}
            <li{% if category.slug == tmp.slug %} class="active"{% endif %}><a href="{% url 'blog:blog-category-archive' slug=tmp.slug %}">{{ tmp.title }}</a></li>
            {% endfor %}
        {% endif %}
        </ul>
    </div>

</div>
{% endblock %}

blog/templates/blog/article/date_archive.html
{% extends "blog/base.html" %}

{% block title %}Blog | Archive: {{ start|date:"M Y" }} {{ block.super }}{% endblock%}

{% block breadcrumb %}
<ul class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li><a href="{% url 'blog:blog-article-index' %}">Blog</a></li>
  <li class="active">Archive: {{ start|date:"M Y" }}</li>
</ul>
{% endblock %}

{% block content %}
<div>
    <div class="col-md-10">
        <h3>Blog Archive: {{ start|date:"d M Y" }} to {{ end|date:"d M Y" }}</h3>
        {% for item in articles %}
            </br>
            <article class="news-item">
                <h4 class="title"><a href="{% url 'blog:blog-article-single' slug=item.slug %}">{{ item.title }}</a></h4>
                <div class="meta">{{ item.date_publish|date:"F j, Y" }}</div>
                <div class="text">
                    <p>{{ item.excerpt|safe }}</p>
                </div>
            </article>
        {% endfor %}

        <div class="pagination pull-right">
            <span class="step-links">
                {% if articles.has_previous %}
                    <a href="?page={{ articles.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ articles.number }} of {{ articles.paginator.num_pages }}.
                </span>

                {% if articles.has_next %}
                    <a href="?page={{ articles.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
        
    </div>

    <div class="col-md-2">
        <ul class="nav nav-list">
        {% if archive_dates|length > 0%}
            <li class="nav-header">Archive Dates</li>
            {% for date in archive_dates %}
            <li{% if date.month == start.month and date.year == start.year %} class="active"{% endif %}><a href="{% url 'blog:blog-date-archive' month=date|date:'m' year=date|date:'Y' %}">{{ date|date:"M Y" }}</a></li>
            {% endfor %}
            <li class="nav-header">Categories</li>
            {% for tmp in categories %}
            <li{% if category.slug == tmp.slug %} class="active"{% endif %}><a href="{% url 'blog:blog-category-archive' slug=tmp.slug %}">{{ tmp.title }}</a></li>
            {% endfor %}
        {% endif %}
        </ul>
    </div>
</div>
{% endblock %}

blog/templates/blog/article/index.html
{% extends "blog/base.html" %}

{% block title %}Blog | {{ block.super }}{% endblock%}

{% block breadcrumb %}
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">Blog</li>
</ul>
{% endblock %}

{% block content %}
<div>
    <div class="col-md-10">
        <h3>Index</h3>
        {% for item in articles %}
            </br>
            <article class="news-item">
                <h4 class="title"><a href="{% url 'blog:blog-article-single' slug=item.slug %}">{{ item.title }}</a></h4>
                <div class="meta">{{ item.date_publish|date:"F j, Y" }}</div>
            </article>
        {% endfor %}
        
        <div class="pagination pull-right">
            <span class="step-links">
                {% if articles.has_previous %}
                    <a href="?page={{ articles.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ articles.number }} of {{ articles.paginator.num_pages }}.
                </span>

                {% if articles.has_next %}
                    <a href="?page={{ articles.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
        
    </div>
    <div class="col-md-2">
        <ul class="nav nav-list">
        {% if archive_dates|length > 0 %}
            <li class="nav-header">Archive Dates</li>
            {% for date in archive_dates %}
                <li><a href="{% url 'blog:blog-date-archive' year=date|date:'Y' month=date|date:'m' %}">{{ date|date:"M Y" }}</a></li>
            {% endfor %}
            
            <li class="nav-header">Categories</li>
            {% for tmp in categories %}
                <li{% if category.slug == tmp.slug %} class="active"{% endif %}><a href="{% url 'blog:blog-category-archive' slug=tmp.slug %}">{{ tmp.title }}</a></li>
            {% endfor %}
        {% endif %}
        </ul>
    </div>

</div>
{% endblock %}

blog/templates/blog/article/single.html
{% extends "blog/base.html" %}

{% block title %}Blog | {{ article.title }} {{ block.super }}{% endblock%}

{% block breadcrumb %}
<ul class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li><a href="{% url 'blog:blog-article-index' %}">Blog</a></li>
  <li class="active">{{ article.title }}</li>
</ul>
{% endblock %}

{% block content %}
<div>
    <div class="col-md-10">
        <h3>{{ article.title }}</h3>
        <p class="meta">{{ article.date_publish|date:"F j, Y" }}</p>
        {{ article.content_markup|safe }}
        <p class="meta">Categories, 
            {% for category in article.categories.all %}
                <a class="btn" href="{% url 'blog:blog-category-archive' slug=category.slug %}">{{ category.title }}</a> 
            {% endfor %}
        </p>
        <hr/>
        
        <!-- Comments -->
        
    </div>
    <div class="col-md-2">
        <ul class="nav nav-list">
        {% if archive_dates|length > 0%}
            
            <li class="nav-header">Archive Dates</li>
            {% for date in archive_dates %}
                <li><a href="{% url 'blog:blog-date-archive' month=date|date:"m" year=date|date:"Y" %}">{{ date|date:"M Y" }}</a></li>
            {% endfor %}
            
            <li class="nav-header">Categories</li>
            {% for tmp in categories %}
                <li{% if category.slug == tmp.slug %} class="active"{% endif %}><a href="{% url 'blog:blog-category-archive' slug=tmp.slug %}">{{ tmp.title }}</a></li>
            {% endfor %}
        {% endif %}
        </ul>
    </div>
</div>
{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">

        <title>{% block title %}{% endblock %}</title>

        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- CSS -->
        <link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet">

        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    </head>

    <body>

        <div id="wrap">
            
            <div class="container">
                <div class="masthead">
                    <h3 class="muted">Blog Site</h3>
                </div>
                {% block breadcrumb %}{% endblock %}
                {% block content %}{% endblock%}
            </div>
            
        </div>

        <!-- Javascript -->
        <script src="{{ STATIC_URL }}js/jquery.min.js"></script>
        <script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
    </body>
</html>